# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

pool:
  vmImage: 'macOS-10.13'

steps:
- script: |
    cd ios/Sandbox
    cp ./mock-GoogleService-Info.plist ./GoogleService-Info.plist
    cd -
  displayName: Copy GoogleService-Info.plist

- script: |
    gem install cocoapods --pre
  displayName: Install cocoapods

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
    projectDirectory: '$(system.defaultWorkingDirectory)/ios'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'Sandbox'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '$(system.defaultWorkingDirectory)/ios/Sandbox.xcworkspace'
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath
