platform :ios, 12.2

use_frameworks!
inhibit_all_warnings!

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Performance'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Phone'
pod 'Fabric'
pod 'Crashlytics'
pod 'R.swift'
pod 'Pulsator'
pod 'PermissionAccess', :git => 'https://github.com/wata/PermissionAccess.git'

target 'Sandbox' do

end

target 'SandboxTests' do
    inherit! :search_paths
end
